# Generated by Django 4.1.4 on 2023-01-21 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='citiesModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_id', models.IntegerField()),
                ('name', models.CharField(max_length=191)),
                ('slug', models.CharField(max_length=191)),
                ('active', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='provincesModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('slug', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='شمار همراه')),
                ('address', models.JSONField(default={'address': [{'State_id': '', 'adder_address': 'پلاک ۳ واحد ۷', 'address': 'مرزداران پشت قنادی ماهبانو', 'call_number': '09372115747', 'cities_id': '', 'company_name': 'namava', 'email': 'em@gmail.com', 'full_name': 'عمران بلوری', 'title': 'خانه'}, {'State_id': '', 'adder_address': 'بن بست بهار', 'address': 'اتوبان حکیم ', 'call_number': '0932214214', 'cities_id': '', 'company_name': 'ارشان', 'email': 'fsa@gma.com', 'full_name': 'رضا بلوری', 'title': 'خانه'}]}, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربری')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
