# Generated by Django 4.1.4 on 2023-01-04 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('call_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت')),
                ('cedit', models.IntegerField(default=0, verbose_name='اعتبار')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='شمار همراه')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/users', verbose_name='عکس پروفایل')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.placeaddressmodel', verbose_name='آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربری')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
