# Generated by Django 4.1.4 on 2023-01-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='cedit',
            new_name='credit',
        ),
    ]
