# Generated by Django 4.1.4 on 2023-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_cedit_profilemodel_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='address',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address1',
            field=models.JSONField(default={'State_id': '', 'adder_address': '', 'address': '', 'call_number': '', 'cities_id': '', 'company_name': '', 'email': '', 'full_name': ''}, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address2',
            field=models.JSONField(default={'State_id': '', 'adder_address': '', 'address': '', 'call_number': '', 'cities_id': '', 'company_name': '', 'email': '', 'full_name': ''}, null=True),
        ),
        migrations.DeleteModel(
            name='PlaceAddressModel',
        ),
    ]
