# Generated by Django 4.1.4 on 2023-01-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profilemodel_address_profilemodel_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='image',
        ),
    ]
