# Generated by Django 4.1.4 on 2023-01-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profilemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='gender',
        ),
    ]
