# Generated by Django 4.1.4 on 2023-01-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profilemodel_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='address2',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='address',
            field=models.JSONField(default={'address': [{'State_id': '', 'adder_address': '', 'address': '', 'call_number': '', 'cities_id': '', 'company_name': '', 'email': '', 'full_name': ''}]}, null=True),
        ),
    ]
