# Generated by Django 4.1.4 on 2023-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profilemodel_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.JSONField(default={'address': [{'State_id': '', 'adder_address': 'پلاک ۳ واحد ۷', 'address': 'مرزداران پشت قنادی ماهبانو', 'call_number': '09372115747', 'cities_id': '', 'company_name': 'namava', 'email': 'em@gmail.com', 'full_name': 'عمران بلوری'}, {'State_id': '', 'adder_address': 'بن بست بهار', 'address': 'اتوبان حکیم ', 'call_number': '0932214214', 'cities_id': '', 'company_name': 'ارشان', 'email': 'fsa@gma.com', 'full_name': 'رضا بلوری'}]}, null=True),
        ),
    ]
