# Generated by Django 4.1.4 on 2023-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profilemodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='citiesModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_id', models.IntegerField()),
                ('name', models.CharField(max_length=191)),
                ('slug', models.CharField(max_length=191)),
                ('active', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ShoppingDB_cities',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.JSONField(default={'address': [{'State_id': '', 'adder_address': 'پلاک ۳ واحد ۷', 'address': 'مرزداران پشت قنادی ماهبانو', 'call_number': '09372115747', 'cities_id': '', 'company_name': 'namava', 'email': 'em@gmail.com', 'full_name': 'عمران بلوری', 'title': 'خانه'}, {'State_id': '', 'adder_address': 'بن بست بهار', 'address': 'اتوبان حکیم ', 'call_number': '0932214214', 'cities_id': '', 'company_name': 'ارشان', 'email': 'fsa@gma.com', 'full_name': 'رضا بلوری', 'title': 'خانه'}]}, null=True),
        ),
    ]
