# Generated by Django 4.1.4 on 2023-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_citiesmodel_alter_profilemodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='provincesModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('slug', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'provinces',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='citiesmodel',
            table='cities',
        ),
    ]
