# Generated by Django 4.1.4 on 2023-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders')),
                ('link', models.CharField(max_length=2048)),
                ('slogan', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=70)),
                ('state', models.CharField(choices=[('sld', 'slider'), ('sub', 'sub banner'), ('sng', 'single banner'), ('sml', 'small banner')], max_length=3)),
            ],
        ),
    ]
