# Generated by Django 4.1.4 on 2023-03-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='slogan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
