# Generated by Django 4.1.4 on 2023-03-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_partcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartCategory',
        ),
    ]
